config/routes.rb
CookiesBlog::Application.routes.draw do

  resources :posts, :only => [:index, :show] do
    resources :coments, :only => [:new, :create]
  end
  root :to => 'posts#index'

end

app/models/coment.rb
class Coment < ActiveRecord::Base
  has_ancestry
  belongs_to :post
  validates :author, :coment, :email, :post_id, :presence => true
  attr_accessible :author, :coment, :email, :post_id, :parent_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
  validates :body, :title, :presence => true
  has_many :coments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController

  def new
  	@post = Post.find params[:post_id]
    if cookies[:remember_me]
  	  @coment = @post.coments.new(
        :parent_id => params[:parent_id],
        :author => cookies[:author],
        :email => cookies[:email])
    else
      @coment = @post.coments.new(:parent_id => params[:parent_id])
    end
  end

  def create
  	@post = Post.find params[:post_id]
  	@coment = @post.coments.build params[:coment]

  	if @coment.save
      cookies_save_if_checked
      redirect_to @post
    else
			render :new
  	end
  end

  private
  def cookies_save_if_checked
    if params[:remember_me]
      cookies[:author] = @coment.author
      cookies[:email] = @coment.email
    else
      cookies.delete :author
      cookies.delete :email
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find params[:id]
  	@coments = @post.coments.arrange
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper

  def nested_comnts(coments)
    coments.map do |coment,sub_coment|
      sub_coments = content_tag(:div, nested_comnts(sub_coment), :class=> "coment nested") if sub_coment.any?
      render(coment) + sub_coments
    end.join.html_safe
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/coments/_coment.html.erb
<div class="coment root">
  <span><%= coment.author %>
    <small>
    ( <%= mail_to coment.email, coment.email.sub("@","(at)") %> )
      <%= coment.created_at.strftime "%e. %-d. %Y %H:%M:%S" %>
    </small>
  </span>
  <%= simple_format coment.coment %>
  <nav>
    <%= link_to "Reply", new_post_coment_path(@post, :parent_id => coment.id) %>
  </nav>
</div>

app/views/coments/create.html.erb
<h1>Coments#create</h1>
<p>Find me in app/views/coments/create.html.erb</p>

app/views/coments/new.html.erb
<h2><%= link_to @post.title, @post %></h2>
<h3>Nový komentar</h3>
<%= form_for [@post,@coment] do |f| %>
	<%= f.hidden_field :parent_id %>
	<ul class="errors">
	<% @coment.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
	</ul>	
	
	<table>
		<tr>
			<td><%= f.label :author %></td>
			<td><%= f.text_field :author  %></td>
		</tr>
		<tr>
			<td><%= f.label :email %></td>
			<td><%= f.text_field :email  %></td>
		</tr>
		<tr>
			<td><%= label_tag :remember_me %></td>
			<td><%= check_box_tag :remember_me, 1, cookies[:author] %></td>
		</tr>
		<tr>
			<td><%= f.label :coment %></td>
			<td><%= f.text_area :coment , :size => "60x5" %></td>
		</tr>
		<tr>
			<td><%= link_to "Späť", @post %></td>
			<td><%= f.submit "Uložiť" %></td>
		</tr>
	</table>    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookiesBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="header">
    <h1><%= link_to "Rails Blog", root_path %> &mdash; Články o Ruby on Rails</h1>
  </div>

	<%= yield %>
</div>
<div class="footer">learn2code :werdyii </div>

</body>
</html>

app/views/posts/_post.html.erb
<h2><%= link_to post.title, post_path(post) %></h2>
<p><%= simple_format post.body %></p>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= simple_format @post.body %></p>

<h3>Komentáre:</h3>
<nav class="commntar">
	<%= link_to "Pridaj komentár", new_post_coment_path(@post)  %>
</nav>
<div class="coments">
	<%if @coments.any? %>
		<%= nested_comnts @coments  %>
	<% else %>
		Tento článok ešte nikto nekomentoval.
	<% end %>
</div>
<nav>
	<%= link_to "Späť", root_path %>
</nav>